// Screen state / menu options
#pragma once

typedef enum {
	SCREEN_MENU,
	SCREEN_SELECT_EDIT,
	SCREEN_SELECT_PLAY,
	SCREEN_LEVEL_EDITOR,
	SCREEN_TEST_PLAY,
	SCREEN_GAME_LEVEL,
	SCREEN_VICTORY,
	SCREEN_DEATH
} ScreenState;

#define MENU_OPTION_COUNT 3
typedef enum {
	MENU_EDIT_EXISTING,
	MENU_CREATE_NEW,
	MENU_PLAY_LEVEL
} MenuOption;
