name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Minimal permissions required for Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Only one deployment at a time
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Ensure submodules initialized
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Verify raylib headers (fallback clone if missing)
        run: |
          set -euxo pipefail
          if [ ! -f vendor/raylib/src/raylib.h ]; then
            echo "raylib.h not found in submodule; cloning upstream as fallback"
            rm -rf vendor/raylib
            git clone --depth 1 https://github.com/raysan5/raylib.git vendor/raylib
          fi
          test -f vendor/raylib/src/raylib.h

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          # Pin a known-good SDK; adjust as needed
          version: 3.1.56

      - name: Build web
        run: |
          make web

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
